$(document).ready(function(){
                $(".main_img_area").mouseenter(function(){
                    $(".main_img_text").fadeToggle(500);
                    $(".search_condition_local").fadeToggle(2000);
                    $(".search_condition_service").fadeToggle(2000);
                    $(".main_img").css("filter", "brightness(30%)");
                    $(".main_img").css("transition", "0.5s");
                });
                $( ".main_img_area").mouseleave(function(){
                    $(".main_img_text").css("display", "block");
                    $(".search_condition_local").css("display", "none");
                    $(".search_condition_service").css("display", "none");
                    $(".main_img").css("filter", "brightness(100%)");
                    $(".local_search").css("display", "none");;
                    $(".service_search").css("display", "none");
                    $(".guid").css("display", "none");
                });
            });
            $(document).ready(function(){
                $( ".search_condition_local").click(function(){
                    $(".search_condition_local").css("display", "none");
                    $(".search_condition_service").css("display", "none");
                    $(".local_search").css("display", "block");
                    $(".local_1").slideDown("slow");
                    $(".guid").slideDown("slow");
                });
                $( ".local_1_0").click(function(){
                    $(".local_2_1").css("display", "none");
                    $(".local_2_2").css("display", "none");
                    $(".local_2_3").css("display", "none");
                    $(".local_2_4").css("display", "none");
                    $(".local_2_6").css("display", "none");
                    $(".local_2_7").css("display", "none");
                    $(".local_2_8").css("display", "none");
                    $(".local_2_9").css("display", "none");
                    $(".local_2_10").css("display", "none");
                    $(".local_2_11").css("display", "none");
                    $(".local_2_12").css("display", "none");
                    $(".local_2_13").css("display", "none");
                    $(".local_2_14").css("display", "none");
                    $(".local_2_15").css("display", "none");
                    $(".local_2_16").css("display", "none");
                });
                $( ".local_1_1").click(function(){
                    $(".local_2_1").slideDown("slow");
                    $(".local_2_2").css("display", "none");
                    $(".local_2_3").css("display", "none");
                    $(".local_2_4").css("display", "none");
                    $(".local_2_5").css("display", "none");
                    $(".local_2_6").css("display", "none");
                    $(".local_2_7").css("display", "none");
                    $(".local_2_8").css("display", "none");
                    $(".local_2_9").css("display", "none");
                    $(".local_2_10").css("display", "none");
                    $(".local_2_11").css("display", "none");
                    $(".local_2_12").css("display", "none");
                    $(".local_2_13").css("display", "none");
                    $(".local_2_14").css("display", "none");
                    $(".local_2_15").css("display", "none");
                    $(".local_2_16").css("display", "none");
                });
                $( ".local_1_2").click(function(){
                    $(".local_2_2").slideDown("slow");
                    $(".local_2_1").css("display", "none");
                    $(".local_2_3").css("display", "none");
                    $(".local_2_4").css("display", "none");
                    $(".local_2_5").css("display", "none");
                    $(".local_2_6").css("display", "none");
                    $(".local_2_7").css("display", "none");
                    $(".local_2_8").css("display", "none");
                    $(".local_2_9").css("display", "none");
                    $(".local_2_10").css("display", "none");
                    $(".local_2_11").css("display", "none");
                    $(".local_2_12").css("display", "none");
                    $(".local_2_13").css("display", "none");
                    $(".local_2_14").css("display", "none");
                    $(".local_2_15").css("display", "none");
                    $(".local_2_16").css("display", "none");
                });
                $( ".local_1_3").click(function(){
                    $(".local_2_3").slideDown("slow");
                    $(".local_2_2").css("display", "none");
                    $(".local_2_1").css("display", "none");
                    $(".local_2_4").css("display", "none");
                    $(".local_2_5").css("display", "none");
                    $(".local_2_6").css("display", "none");
                    $(".local_2_7").css("display", "none");
                    $(".local_2_8").css("display", "none");
                    $(".local_2_9").css("display", "none");
                    $(".local_2_10").css("display", "none");
                    $(".local_2_11").css("display", "none");
                    $(".local_2_12").css("display", "none");
                    $(".local_2_13").css("display", "none");
                    $(".local_2_14").css("display", "none");
                    $(".local_2_15").css("display", "none");
                    $(".local_2_16").css("display", "none");
                });
                $( ".local_1_4").click(function(){
                    $(".local_2_4").slideDown("slow");
                    $(".local_2_2").css("display", "none");
                    $(".local_2_3").css("display", "none");
                    $(".local_2_1").css("display", "none");
                    $(".local_2_5").css("display", "none");
                    $(".local_2_6").css("display", "none");
                    $(".local_2_7").css("display", "none");
                    $(".local_2_8").css("display", "none");
                    $(".local_2_9").css("display", "none");
                    $(".local_2_10").css("display", "none");
                    $(".local_2_11").css("display", "none");
                    $(".local_2_12").css("display", "none");
                    $(".local_2_13").css("display", "none");
                    $(".local_2_14").css("display", "none");
                    $(".local_2_15").css("display", "none");
                    $(".local_2_16").css("display", "none");
                });
                $( ".local_1_5").click(function(){
                    $(".local_2_1").css("display", "none");
                    $(".local_2_2").css("display", "none");
                    $(".local_2_3").css("display", "none");
                    $(".local_2_4").css("display", "none");
                    $(".local_2_6").css("display", "none");
                    $(".local_2_7").css("display", "none");
                    $(".local_2_8").css("display", "none");
                    $(".local_2_9").css("display", "none");
                    $(".local_2_10").css("display", "none");
                    $(".local_2_11").css("display", "none");
                    $(".local_2_12").css("display", "none");
                    $(".local_2_13").css("display", "none");
                    $(".local_2_14").css("display", "none");
                    $(".local_2_15").css("display", "none");
                    $(".local_2_16").css("display", "none");
                });
                $( ".local_1_6").click(function(){
                    $(".local_2_6").slideDown("slow");
                    $(".local_2_2").css("display", "none");
                    $(".local_2_3").css("display", "none");
                    $(".local_2_4").css("display", "none");
                    $(".local_2_5").css("display", "none");
                    $(".local_2_1").css("display", "none");
                    $(".local_2_7").css("display", "none");
                    $(".local_2_8").css("display", "none");
                    $(".local_2_9").css("display", "none");
                    $(".local_2_10").css("display", "none");
                    $(".local_2_11").css("display", "none");
                    $(".local_2_12").css("display", "none");
                    $(".local_2_13").css("display", "none");
                    $(".local_2_14").css("display", "none");
                    $(".local_2_15").css("display", "none");
                    $(".local_2_16").css("display", "none");
                });
                $( ".local_1_7").click(function(){
                    $(".local_2_7").slideDown("slow");
                    $(".local_2_2").css("display", "none");
                    $(".local_2_3").css("display", "none");
                    $(".local_2_4").css("display", "none");
                    $(".local_2_5").css("display", "none");
                    $(".local_2_6").css("display", "none");
                    $(".local_2_1").css("display", "none");
                    $(".local_2_8").css("display", "none");
                    $(".local_2_9").css("display", "none");
                    $(".local_2_10").css("display", "none");
                    $(".local_2_11").css("display", "none");
                    $(".local_2_12").css("display", "none");
                    $(".local_2_13").css("display", "none");
                    $(".local_2_14").css("display", "none");
                    $(".local_2_15").css("display", "none");
                    $(".local_2_16").css("display", "none");
                });
                $( ".local_1_8").click(function(){
                    $(".local_2_8").slideDown("slow");
                    $(".local_2_2").css("display", "none");
                    $(".local_2_3").css("display", "none");
                    $(".local_2_4").css("display", "none");
                    $(".local_2_5").css("display", "none");
                    $(".local_2_6").css("display", "none");
                    $(".local_2_7").css("display", "none");
                    $(".local_2_1").css("display", "none");
                    $(".local_2_9").css("display", "none");
                    $(".local_2_10").css("display", "none");
                    $(".local_2_11").css("display", "none");
                    $(".local_2_12").css("display", "none");
                    $(".local_2_13").css("display", "none");
                    $(".local_2_14").css("display", "none");
                    $(".local_2_15").css("display", "none");
                    $(".local_2_16").css("display", "none");
                });
                $( ".local_1_9").click(function(){
                    $(".local_2_9").slideDown("slow");
                    $(".local_2_2").css("display", "none");
                    $(".local_2_3").css("display", "none");
                    $(".local_2_4").css("display", "none");
                    $(".local_2_5").css("display", "none");
                    $(".local_2_6").css("display", "none");
                    $(".local_2_7").css("display", "none");
                    $(".local_2_8").css("display", "none");
                    $(".local_2_1").css("display", "none");
                    $(".local_2_10").css("display", "none");
                    $(".local_2_11").css("display", "none");
                    $(".local_2_12").css("display", "none");
                    $(".local_2_13").css("display", "none");
                    $(".local_2_14").css("display", "none");
                    $(".local_2_15").css("display", "none");
                    $(".local_2_16").css("display", "none");
                });
                $( ".local_1_10").click(function(){
                    $(".local_2_10").slideDown("slow");
                    $(".local_2_2").css("display", "none");
                    $(".local_2_3").css("display", "none");
                    $(".local_2_4").css("display", "none");
                    $(".local_2_5").css("display", "none");
                    $(".local_2_6").css("display", "none");
                    $(".local_2_7").css("display", "none");
                    $(".local_2_8").css("display", "none");
                    $(".local_2_9").css("display", "none");
                    $(".local_2_1").css("display", "none");
                    $(".local_2_11").css("display", "none");
                    $(".local_2_12").css("display", "none");
                    $(".local_2_13").css("display", "none");
                    $(".local_2_14").css("display", "none");
                    $(".local_2_15").css("display", "none");
                    $(".local_2_16").css("display", "none");
                });
                $( ".local_1_11").click(function(){
                    $(".local_2_11").slideDown("slow");
                    $(".local_2_2").css("display", "none");
                    $(".local_2_3").css("display", "none");
                    $(".local_2_4").css("display", "none");
                    $(".local_2_5").css("display", "none");
                    $(".local_2_6").css("display", "none");
                    $(".local_2_7").css("display", "none");
                    $(".local_2_8").css("display", "none");
                    $(".local_2_9").css("display", "none");
                    $(".local_2_10").css("display", "none");
                    $(".local_2_1").css("display", "none");
                    $(".local_2_12").css("display", "none");
                    $(".local_2_13").css("display", "none");
                    $(".local_2_14").css("display", "none");
                    $(".local_2_15").css("display", "none");
                    $(".local_2_16").css("display", "none");
                });
                $( ".local_1_12").click(function(){
                    $(".local_2_12").slideDown("slow");
                    $(".local_2_2").css("display", "none");
                    $(".local_2_3").css("display", "none");
                    $(".local_2_4").css("display", "none");
                    $(".local_2_5").css("display", "none");
                    $(".local_2_6").css("display", "none");
                    $(".local_2_7").css("display", "none");
                    $(".local_2_8").css("display", "none");
                    $(".local_2_9").css("display", "none");
                    $(".local_2_10").css("display", "none");
                    $(".local_2_11").css("display", "none");
                    $(".local_2_1").css("display", "none");
                    $(".local_2_13").css("display", "none");
                    $(".local_2_14").css("display", "none");
                    $(".local_2_15").css("display", "none");
                    $(".local_2_16").css("display", "none");
                });
                $( ".local_1_13").click(function(){
                    $(".local_2_13").slideDown("slow");
                    $(".local_2_2").css("display", "none");
                    $(".local_2_3").css("display", "none");
                    $(".local_2_4").css("display", "none");
                    $(".local_2_5").css("display", "none");
                    $(".local_2_6").css("display", "none");
                    $(".local_2_7").css("display", "none");
                    $(".local_2_8").css("display", "none");
                    $(".local_2_9").css("display", "none");
                    $(".local_2_10").css("display", "none");
                    $(".local_2_11").css("display", "none");
                    $(".local_2_12").css("display", "none");
                    $(".local_2_1").css("display", "none");
                    $(".local_2_14").css("display", "none");
                    $(".local_2_15").css("display", "none");
                    $(".local_2_16").css("display", "none");
                });
                $( ".local_1_14").click(function(){
                    $(".local_2_14").slideDown("slow");
                    $(".local_2_2").css("display", "none");
                    $(".local_2_3").css("display", "none");
                    $(".local_2_4").css("display", "none");
                    $(".local_2_5").css("display", "none");
                    $(".local_2_6").css("display", "none");
                    $(".local_2_7").css("display", "none");
                    $(".local_2_8").css("display", "none");
                    $(".local_2_9").css("display", "none");
                    $(".local_2_10").css("display", "none");
                    $(".local_2_11").css("display", "none");
                    $(".local_2_12").css("display", "none");
                    $(".local_2_13").css("display", "none");
                    $(".local_2_1").css("display", "none");
                    $(".local_2_15").css("display", "none");
                    $(".local_2_16").css("display", "none");
                });
                $( ".local_1_15").click(function(){
                    $(".local_2_15").slideDown("slow");
                    $(".local_2_2").css("display", "none");
                    $(".local_2_3").css("display", "none");
                    $(".local_2_4").css("display", "none");
                    $(".local_2_5").css("display", "none");
                    $(".local_2_6").css("display", "none");
                    $(".local_2_7").css("display", "none");
                    $(".local_2_8").css("display", "none");
                    $(".local_2_9").css("display", "none");
                    $(".local_2_10").css("display", "none");
                    $(".local_2_11").css("display", "none");
                    $(".local_2_12").css("display", "none");
                    $(".local_2_13").css("display", "none");
                    $(".local_2_14").css("display", "none");
                    $(".local_2_1").css("display", "none");
                    $(".local_2_16").css("display", "none");
                });
                $( ".local_1_16").click(function(){
                    $(".local_2_16").slideDown("slow");
                    $(".local_2_2").css("display", "none");
                    $(".local_2_3").css("display", "none");
                    $(".local_2_4").css("display", "none");
                    $(".local_2_5").css("display", "none");
                    $(".local_2_6").css("display", "none");
                    $(".local_2_7").css("display", "none");
                    $(".local_2_8").css("display", "none");
                    $(".local_2_9").css("display", "none");
                    $(".local_2_10").css("display", "none");
                    $(".local_2_11").css("display", "none");
                    $(".local_2_12").css("display", "none");
                    $(".local_2_13").css("display", "none");
                    $(".local_2_14").css("display", "none");
                    $(".local_2_15").css("display", "none");
                    $(".local_2_1").css("display", "none");
                });
                $( ".local_1_17").click(function(){
                    $(".local_2_2").css("display", "none");
                    $(".local_2_3").css("display", "none");
                    $(".local_2_4").css("display", "none");
                    $(".local_2_1").css("display", "none");
                    $(".local_2_6").css("display", "none");
                    $(".local_2_7").css("display", "none");
                    $(".local_2_8").css("display", "none");
                    $(".local_2_9").css("display", "none");
                    $(".local_2_10").css("display", "none");
                    $(".local_2_11").css("display", "none");
                    $(".local_2_12").css("display", "none");
                    $(".local_2_13").css("display", "none");
                    $(".local_2_14").css("display", "none");
                    $(".local_2_15").css("display", "none");
                    $(".local_2_16").css("display", "none");
                });
            });
            $(document).ready(function(){
                $( ".search_condition_service").click(function(){
                    $(".search_condition_local").css("display", "none");
                    $(".search_condition_service").css("display", "none");
                    $(".service_search").css("display", "block");
                    $(".service_1").slideDown("slow");
                    $(".guid").slideDown("slow");
                });
            });